[package]
name = "code-errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checked_command = "0.2.4"
openai-api = "0.1.4"
dotenv = "0.15.0"
tokio = { version = "0.2", features = ["full"] }
